# Generated by Django 4.0.2 on 2022-06-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNoticias', '0002_servicios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Plantas',
        ),
        migrations.AlterModelOptions(
            name='plantas',
            options={'verbose_name_plural': 'Plantas'},
        ),
    ]
