# Generated by Django 4.0.2 on 2022-06-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNoticias', '0003_rename_noticia_plantas_alter_plantas_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
